### ISSUE TITLE
RangeError: TextDecoder constructor: The given encoding is not supported.

### ISSUE THREAD

**Issue by bcastagna** [calvinmetcalf/shapefile-js#136]
Hi

First, thanks for this package, it's very handy :+1: :100: 

Recently we encountered an issue which appears only on our built for prod with AOT enabled angular app : 

`shp('assets/shape-files/' + this.placeName).then((geojson: Object) => {
          console.log("Geojson retrieved " + geojson);
          this.serviceParams['placeName'] = this.placeName;
          this.placeGeoJson = geojson;
          this.loadMap();
        },
        (error: any) => {
          this.nbToastrService.show(
            'Error while retrieving shape file ! Check console.',
            'Error',
            {status: 'danger'}
          );
          console.log(error);
        });`

![image](https://user-images.githubusercontent.com/3739556/93728675-eb4f6c00-fb8e-11ea-9a43-3ae8b4f38742.png)

We have searched for an explanation for hours but still can find one.
Few info:
- We have this built angular app running on a classic apache on staging (where it does not work)
- We have built the app exactly how it is built for staging and make it run in dev: no problem.
- We have the app running in dev (ng serve) without any single problem.
- 'assets/shape-files/shape.shp' is readable and available in every envs.

Please help. What could it be ?? :(

**Comment by calvinmetcalf** [comment]
I believe the issue is that you are not properly returning 404 errors on your server, I believe you are just returning the app page for all other routes when in reality you are going to want to give 404s for anything in the assets folder that you cant' find.

stepping back whats happening is that you pass it a path and it looks for the files with `.shp`, `.dbf`, `.prj`, `.cpg` extensions, the last 2 being optional and we  assume we didn't get them if we get a 400 or higher status cope, but your server is just returning a 200 and the web app page for all requests it doesn't know about.   So as a stop gap, just put a file with your shapefile called {shapefileName}.cpg that contains the text `utf8` and longer term I can update this library to just ignore invalid text encoding

**Comment by bcastagna** [comment]
In deed that's the only thing that could differ from between our local ng serve and staging's apache.
Ok im going to build with the latest release and dig your hints and updated this thread if other people run into this issue.
Thanks a lot, much appreciated !! :+1:

**Comment by bcastagna** [comment]
I confirm it works with last release 3.6.0 (without having put the missing {shapefileName}.cpg) ... and in deed I had a 404 with the CPG file in dev i didnt notice... Thanks again ! :+1:
