### ISSUE TITLE
problems when parse .shp file 

### ISSUE THREAD

**Issue by 850036165** [calvinmetcalf/shapefile-js#218]
i am using shp.js in my project to parse shp file.
here are some conditions
```
import shp from 'shpjs'

// upload test.shp file with input
function handleBeforeUpload(file: File): Promise<boolean> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.readAsArrayBuffer(file)
    reader.onload = async (e) => {
      const arrayBuffer = e.target?.result

 geojson = await shp({ shp: arrayBuffer }) 
// good

geojson1 = await shp('https://file.tankmiles.com/test/POLYGON.shp') 
// good

geojson2 = shp.parseShp(arrayBuffer) 
// Error TypeError: shp.parseShp is not a function

geojson3 = await shp(arrayBuffer) 
// Error hook.js:591  Error: but-unzip~2
```

**Comment by calvinmetcalf** [comment]
when you are uploading it, you're just passing the `.shp` file but not the `.prj` or `.dbf` so it works but there are not any attributes, when you grab it from the url it also grabs the `https://file.tankmiles.com/test/POLYGON.dbf` etc.  You can't do thing 2 because that function isn't exported anymore, and thing 3 doens't work because it expects a `.zip` so either upload a zip, or grab the shp and dbf and pass them in the object like you did in example 0.

**Comment by matteomelotti** [comment]
I have a similar issue with every example I'm trying.
I always receive `Error processing shapefile: TypeError: (0 , shpjs_1.default) is not a function`; I'm using Typescript but nothing changes if I install `@types/shpjs`

**Comment by calvinmetcalf** [comment]
You have a different issue Matteo, possibly related to imports in type
script or something? I'm not sure we definitely have a default were
exporting.

-Calvin W. Metcalf
