### ISSUE TITLE
Geometry in original projection

### ISSUE THREAD

**Issue by craigsnyders** [calvinmetcalf/shapefile-js#62]
It would be useful for me to have the geojson output using the original geometry.  Perhaps we could add the `crs` property on the geojson object.

Many .prj files unfortunately do not include an AUTHORITY string, so instead of adding the `crs` property perhaps just return the proj4 transformation function in a promise with the geojson.

This will reduce loss of precision, if the map already uses the original projection.  In my case, there is a non-negligible loss between `EPSG:27700` >> `EPSG:4326` >> `EPSG:27700`

E.G. I want to do:
```javascript
shp(arrayBuffer).then(function(geojson, proj) {
  // use the geojson AND projection function
});
```

**Comment by calvinmetcalf** [comment]
yeah I mean this is intended from some pretty basic use cases, I recommend [shapefile](https://github.com/mbostock/shapefile) for advanced use cases

**Comment by craigsnyders** [comment]
This library's tagline is 'Not many caveats'.  Automatically reprojecting to WGS84 is a big caveat for anybody using non-WGS84 maps - E.G. the whole of Europe or UK.

Anyway, I'm willing to create a PR so why not leave this open?

**Comment by calvinmetcalf** [comment]
This is really not intended for 'serious GIS stuff' but to convert to GeoJSON and 'just work' I'm generally against having complex options for edge cases *in this library* there are other shapefile libraries that handle more complex things like streaming shapefiles and other more complex things.  What you want can actually be done with the current library by unzipping yourself and then passing the dbf and shp buffers to the 
```js
shp.combine([shp.parseShp(shpBuffer), shp.parseDbf(dbfBuffer)]);
```

you could totally write a module to achieve what you want based on this one, due to how promises work

```js
yourShpMod(arrayBuffer).then(function(geojson, proj) {
  // use the geojson AND projection function
});
```

would probably not work, but 

```js
yourShpMod(arrayBuffer, outproj).then(function(geojson, proj) {
  // use the geojson projected directly to the outgoing projection
});
```

might be a better api for that

**Comment by craigsnyders** [comment]
Thanks for the response, it's been very useful.  I understand your reasoning better now too.  

It isn't very clear in the docs that `shp.combine` doesn't reproject the data to WGS84 (when a .prj is present), whereas shp() does.  In hindsight that makes perfect sense.

I unzipped the file myself to get access to the .prj file to use with Proj4, if present. Works perfectly
